### PR TITLE
Fix BitBucket line href

### PR DESCRIPTION
**Pull request by dolzenko**

### CODE REVIEW

**Comment by sshaw** [comment]
Thanks for this. Do you know if their latest change allows one to link to a start and end line?

**Comment by dolzenko** [comment]
@sshaw not sure, you mean linking file HREFs on commit page, like https://bitbucket.org/jespern/django-piston/commits/7c90898072ce9462a6023bbec5d408ad097a362b#chg-piston/tests.py ?

**Comment by sshaw** [comment]
No, linking like GitHub allows, [like this](https://github.com/sshaw/git-link/blob/master/git-link.el#L3-6).

**Comment by dolzenko** [comment]
Ah, sure, no they don't seem to at the moment https://bitbucket.org/site/master/issues/10622/url-link-to-multiple-lines-with-cl-xx-yy

**Comment by sshaw** [comment]
This has been released with `v0.2.1`.

Can't believe that BitBucket *still* does not have :question: :hash: :exclamation: multiline linking. Shit has been going on [since 2009](https://bitbucket.org/site/master/issues/444/make-linenumbers-in-source-view-link-to-cl).

**Pull request merged**
