### PR TITLE
Travis CI coverage for Emacs 27; Travis CI uses Nix

### PR DESCRIPTION
**Pull request by peterbecich**
Uses https://github.com/purcell/nix-emacs-ci now

### CODE REVIEW

**Comment by sshaw** [comment]
Ooooh Nix, nice...

**Comment by peterbecich** [comment]
@sshaw , please review

**Comment by sshaw** [comment]
@peterbecich thanks a lot. I recently updated Travis CI config for [rvm.el](https://github.com/senny/rvm.el) and saw that the Old Method ™️ didn't have the latest version so definitely will be using this there too!

Just one request: can you squash into a single commit?

Thanks! 💪

**Comment by peterbecich** [comment]
@sshaw very good, done

**Comment by sshaw** [comment]
One thing I just noticed is that [we explicitly call `make build`](https://github.com/sshaw/git-link/pull/74/files#diff-354f30a63fb0907d4ad57269548329e3R58). Since `make test` has `build` as a prerequisite, is there a reason to call it explicitly?

Merging regardless!

**Pull request merged**
